### ISSUE TITLE
'CLOCK_SPEED_100KHZ' was not declared in this scope

### ISSUE THREAD

**Issue by dominikkv** [BulldogLowell/LiquidCrystal_I2C_Spark#2]
Veryfing code using this library in Particle Build fails with this error:

```
LiquidCrystal_I2C_Spark/LiquidCrystal_I2C_Spark.cpp:48:23: error: 'CLOCK_SPEED_100KHZ' was not declared in this scope
         Wire.setSpeed(CLOCK_SPEED_100KHZ)
```

**Comment by BulldogLowell** [comment]
I get my Photons this week, I'll have a look at the lib once I get them...  I'm sure its related to that.

**Comment by dominikkv** [comment]
Yes I try to compile for Photon. Thanks!

**Comment by redelectrical** [comment]
Yes I'm getting this error too

**Comment by qwerty009** [comment]
Got same problem, it would be great if someone could fix it and point out what the problem was (i have one local i2c library that has same error with photon).

**Comment by dominikkv** [comment]
Particle Forums https://community.particle.io/t/trouble-getting-liquidcrystal-i2c-spark-library-to-work/13178

It seems that the Photon needs a firmware update. Workaround and a temp repository with this workaround in linked thread.

**Comment by dominikkv** [comment]
Seems to compile with firmware 0.4.4
